Traceback (most recent call last):
  File "debugging.py", line 52, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "debugging.py", line 52, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "debugging.py", line 52, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
